{% set name = "libass" %}
{% set version = "0.15.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/libass/libass/releases/download/{{ version }}/libass-{{ version }}.tar.xz
  sha256: 1cdd39c9d007b06e737e7738004d7f38cf9b1e92843f37307b24e7ff63ab8e53

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - make
    - autoconf
    - automake
    - pkg-config
    - libtool
  host:
    - nasm
    - perl
    - freetype
    - fribidi
    - fontconfig
    - expat
    - zlib
    - harfbuzz
  run:
    - freetype
    - fribidi
    - fontconfig
    - expat
    - zlib
    - harfbuzz

test:
  commands:
    - test -f $PREFIX/lib/libass$SHLIB_EXT  # [unix]

about:
  home: https://github.com/libass/libass
  license: ISC
  license_family: OTHER
  license_file: COPYING
  summary: A portable subtitle renderer for the ASS/SSA (Advanced Substation Alpha/Substation Alpha) subtitle format.
  doc_url: https://github.com/libass/libass
  dev_url: https://github.com/libass/libass

extra:
  recipe-maintainers:
    - scopatz
