{% set name = "libass" %}
{% set version = "0.15.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/libass/libass/releases/download/{{ version }}/libass-{{ version }}.tar.xz
  sha256: 9f09230c9a0aa68ef7aa6a9e2ab709ca957020f842e52c5b2e52b801a7d9e833

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - make
    - autoconf
    - automake
    - pkg-config
    - libtool
  host:
    - nasm
    - perl
    - freetype
    - fribidi
    - fontconfig
    - expat
    - zlib
    - harfbuzz
  run:
    - freetype
    - fribidi
    - fontconfig
    - expat
    - zlib
    - harfbuzz

test:
  commands:
    - test -f $PREFIX/lib/libass$SHLIB_EXT  # [unix]

about:
  home: https://github.com/libass/libass
  license: ISC
  license_family: OTHER
  license_file: COPYING
  summary: A portable subtitle renderer for the ASS/SSA (Advanced Substation Alpha/Substation Alpha) subtitle format.
  doc_url: https://github.com/libass/libass
  dev_url: https://github.com/libass/libass

extra:
  recipe-maintainers:
    - scopatz
