{% set name = "libass" %}
{% set version = "0.17.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/libass/libass/releases/download/{{ version }}/libass-{{ version }}.tar.xz
  sha256: eae425da50f0015c21f7b3a9c7262a910f0218af469e22e2931462fed3c50959

build:
  number: 1
  skip: true  # [win]
  run_exports:
    - {{ pin_subpackage('libass', max_pin='x.x.x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - make
    - autoconf
    - automake
    - pkg-config
    - libtool
    - nasm
  host:
    - freetype
    - fribidi
    - fontconfig
    - libexpat
    - libiconv
    # - zlib
    - harfbuzz

test:
  commands:
    - test -f $PREFIX/lib/libass$SHLIB_EXT  # [unix]

about:
  home: https://github.com/libass/libass
  license: ISC
  license_family: OTHER
  license_file: COPYING
  summary: A portable subtitle renderer for the ASS/SSA (Advanced Substation Alpha/Substation Alpha) subtitle format.
  doc_url: https://github.com/libass/libass
  dev_url: https://github.com/libass/libass

extra:
  recipe-maintainers:
    - Tobias-Fischer
    - scopatz
